import { Product } from './products.types';

export const productSeed: Product[] = [
  {
    id: 'prod-1001',
    name: 'Aurora Wireless Headphones',
    description: 'Noise-cancelling over-ear headphones with 40-hour battery life.',
    category: 'electronics',
    price: 189,
    currency: 'SGD',
    stock: 15,
    featured: true,
    imageUrl: 'https://example.com/images/aurora-headphones.jpg',
    sku: 'ELE-AUR-001',
  },
  {
    id: 'prod-1002',
    name: 'Lumen Desk Lamp',
    description: 'Minimal LED desk lamp with warm and cool brightness modes.',
    category: 'home',
    price: 79,
    currency: 'SGD',
    stock: 28,
    featured: false,
    imageUrl: 'https://example.com/images/lumen-lamp.jpg',
    sku: 'HOM-LUM-002',
  },
  {
    id: 'prod-1003',
    name: 'Stride Running Shoes',
    description: 'Lightweight trainers built for daily road runs and long walks.',
    category: 'sports',
    price: 129,
    currency: 'SGD',
    stock: 22,
    featured: true,
    imageUrl: 'https://example.com/images/stride-shoes.jpg',
    sku: 'SPT-STR-003',
  },
  {
    id: 'prod-1004',
    name: 'Canvas Utility Tote',
    description: 'Everyday tote bag with laptop sleeve and zippered inner pocket.',
    category: 'fashion',
    price: 58,
    currency: 'SGD',
    stock: 34,
    featured: false,
    imageUrl: 'https://example.com/images/canvas-tote.jpg',
    sku: 'FSH-CAN-004',
  },
  {
    id: 'prod-1005',
    name: 'Botanical Repair Serum',
    description: 'Hydrating face serum with niacinamide and centella extract.',
    category: 'beauty',
    price: 46,
    currency: 'SGD',
    stock: 41,
    featured: true,
    imageUrl: 'https://example.com/images/repair-serum.jpg',
    sku: 'BEA-BOT-005',
  },
];
